// +build ignore

package main

import (
	"io/ioutil"
	"log"
	"os"
	"text/template"
	"time"
)

var mainTmpl = `
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// {{ .Time }}
package main

var feedTmpl = ` + "`{{.Body}}`" + `
`

func main() {
	tmpl, err := template.New("template").Parse(mainTmpl)
	if err != nil {
		log.Fatalf("could not parse template: %v", err)
	}
	body, err := ioutil.ReadFile("template.html")
	if err != nil {
		log.Fatalf("could not open template: %v", err)
	}
	w, err := os.Create("template.go")
	if err != nil {
		log.Fatalf("could not create generated template file: %v", err)
	}
	data := struct {
		Time time.Time
		Body string
	}{time.Now(), string(body)}
	if err := tmpl.Execute(w, data); err != nil {
		log.Fatalf("could not execute template: %v", err)
	}
}
