// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2019-07-01 14:22:17.792151 +0200 CEST m=+0.000789331
package main

var feedTmpl = `<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="robots" content="noindex">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>{{.Category | sanitize}}</title>

	<style type="text/css">
		body {
			margin: 0 auto;
			max-width: 1024px;
			padding: .5rem;
			font-weight: lighter;
		}

		a {
			color: blue;
			text-decoration: none;
		}

		a:hover {
			color: darkblue;
			text-decoration: underline;
		}

		ul {
			padding: 0;
		}

		ul li {
			display: inline;
			list-style: none;
		}

		article {
			margin-bottom: .5rem;
		}

		article>h2 {
			margin-bottom: 0;
		}

		footer,
		article>small {
			color: #666;
		}

		article>p {
			line-height: 1.5;
			word-break: break-word;
		}

		h1,
		ul li,
		article>*,
		footer {
			margin: 0;
			margin-bottom: .5rem;
			padding: .25rem;
		}
	</style>
</head>

<body>
	<h1>{{.Category | sanitize }}</h1>

	<ul>
		{{range .Categories}}
		<li><a href="{{.}}.html">{{.}}</a></li>
		{{end}}
	</ul>

	{{range .Items}}
	<article>
		<h2>
			<a href="{{.Link}}" target="_blank">{{.Title | sanitize | trim}}</a>
		</h2>
		<small>
			by <a href="{{.Feed.Link | hash}}.html">{{.Feed.Title | sanitize | trim}}</a>
			in <a href="{{.Category}}.html">{{.Category}}</a>
			on {{.Time.Format "02. Jan 2006"}}
		</small>
		<p>
			{{.Description | sanitize | trim | truncate}}
			{{.Content | sanitize | trim | truncate}}
		</p>
	</article>
	{{end}}

	<footer>
		Updated {{time.Format "02. Jan 2006 at 15:04"}}. Version {{.Version}}.
	</footer>
</body>

</html>`
